on:
  push:
    branches: main
  pull_request:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
  
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::here
            any::mlr3pipelines
            any::torch
            any::mlr3
            any::remotes

      - name: Install remotes package
        run: |
          Rscript -e 'install.packages("remotes")'

      - name: Install mlr3torch from GitHub
        run: |
          Rscript -e 'remotes::install_github("mlr-org/mlr3torch")'
      
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
