project:
  output-dir: docs

toc: true
number-sections: true
bibliography: references.bib  
format:
  revealjs:
    theme:
      - simple
    logo: "images/mardi-logo.png"
    code-copy: false
    height: 1080
    width: 1980
    slide-number: c/t
    center-title-slide: false
    higlight-style: atom-one
    footer: "UseR 2024"
